from main import Question

questions_test_2 = [
    Question(1, "Aldehyde sind",
             ["Oxidationsprodukte von sekundären Alkoholen", "Stickstoffverbindungen", "Kohlenstoffverbindungen",
              "Reduktionsprodukte von Carbonsäuren"],
             [2, 3]),
    Question(2, "Aldehyde sind",
             ["Oxidationsprodukte von primären Alkoholen", "anorganische Verbindungen", "Kohlenstoffverbindungen",
              "Oxidationsprodukte von Carbonsäuren"],
             [0, 2]),
    Question(3, "Aldehyde haben als funktionelle Gruppe",
             ["–COOH", "–CHO", "–C-OH", "–CO-"],
             [1]),
    Question(4, "Zu den Carbonsäuren gehört",
             ["Mineralsäure", "Ethansäure", "Schwefelsäure", "Weinsäure"],
             [1, 3]),
    Question(5, "Zu den organischen Säuren gehört die",
             ["Ameisensäure mit 2-C-Atomen", "Essigsäure mit einem C-Atom", "Milchsäure mit 3 C-Atomen",
              "Zitronensäure mit 6 C-Atomen"],
             [2, 3]),
    Question(6, "Methansäure besitzt",
             ["ein C-Atom", "zwei O-Atome", "drei C-Atome", "vier H-Atome"],
             [0, 1]),
    Question(7, "Methansäure hat ein Molekulargewicht von",
             ["25 u (+/-1u)", "35 u (+/-1u)", "45 u (+/-1u)", "15 u (+/-1u)"],
             [2]),
    Question(8, "Ameisensäure beinhaltet",
             ["ein C-Atom", "zwei C-Atome", "drei C-Atome", "kein C-Atom"],
             [0]),
    Question(9, "Ethansäure besitzt",
             ["ein C-Atom", "zwei O-Atome", "drei C-Atome", "vier H-Atome"],
             [1, 3]),
    Question(10, "Linolensäure",
             ["hat 16 C-Atome", "hat mehrere Doppelbindungen",
              "ist essentiell für die Entwicklung des Nervensystems", "ist eine alpha-3-Fettsäure"],
             [1, 2]),
    Question(11, "Zitronensäure",
             ["hat 8 C-Atome", "wird aus Aspergillus niger hergestellt", "ist eine Dicarbonsäure",
              "wird auch als Entkalkungsmittel verwendet"],
             [1, 3]),
    Question(12, "Zitronensäure",
             ["hat 6 C-Atome", "wird biotechnologisch aus Schimmelpilzen hergestellt", "ist eine Dicarbonsäure",
              "wird auch als Lebensmittelzusatzstoff verwendet"],
             [0, 1, 3]),
    Question(13, "Das asymmetrische C-Atom ist eine Voraussetzung für",
             ["Chiralität", "Liquidität", "optische Aktivität", "Parität"],
             [0, 2]),
    Question(14, "Optisch aktive Substanzen können nach folgenden Formen unterschieden werden",
             ["H- und U-Form", "D- und L- Form", "R- und S-Form", "alpha- und beta-Form"],
             [1, 2]),
    Question(15, "Fruchtester sind",
             ["Ester aus kurzkettigen Carbonsäuren und Alkoholen",
              "Ester aus langkettigen Carbonsäuren und langkettigen Alkoholen",
              "Ester aus langkettigen Carbonsäuren und dem dreiwertigen Alkohol Glycerol",
              "Ester zwischen mehrwertigen Carbonsäuren und mehrwertigen Alkoholen"],
             [0]),
    Question(16, "Wachse sind",
             ["Ester aus kurzkettigen Carbonsäuren und Alkoholen",
              "Ester aus langkettigen Carbonsäuren und langkettigen Alkoholen",
              "Ester aus langkettigen Carbonsäuren und dem dreiwertigen Alkohol Glycerol",
              "Ester zwischen mehrwertigen Carbonsäuren und mehrwertigen Alkoholen"],
             [1]),
    Question(17, "Fette sind",
             ["Ester aus kurzkettigen Carbonsäuren und Alkoholen",
              "Ester aus langkettigen Carbonsäuren und langkettigen Alkoholen",
              "Ester aus langkettigen Carbonsäuren und dem dreiwertigen Alkohol Glycerol",
              "Ester zwischen mehrwertigen Carbonsäuren und mehrwertigen Alkoholen"],
             [2]),
    Question(18, "Öle sind",
             ["Ester aus kurzkettigen Carbonsäuren und Alkoholen",
              "Ester aus langkettigen Carbonsäuren und langkettigen Alkoholen",
              "Ester aus langkettigen Carbonsäuren und dem dreiwertigen Alkohol Glycerol",
              "Ester zwischen mehrwertigen Carbonsäuren und mehrwertigen Alkoholen"],
             [2]),
    Question(19, "Polyester sind",
             ["Ester aus kurzkettigen Carbonsäuren und Alkoholen",
              "Ester aus langkettigen Carbonsäuren und langkettigen Alkoholen",
              "Ester aus langkettigen Carbonsäuren und dem dreiwertigen Alkohol Glycerol",
              "Ester zwischen mehrwertigen Carbonsäuren und mehrwertigen Alkoholen"],
             [3]),
    Question(20, "Zu den pflanzlichen Wachsen gehört",
             ["Lanolinwachs", "Paraffinwachs", "Karnaubawachs", "Jojobawachs"],
             [2, 3]),
    Question(21, "Zu den tierischen Wachsen gehört",
             ["Lanolinwachs", "Paraffinwachs", "Karnaubawachs", "Jojobawachs"],
             [0]),
    Question(22, "Zum zentralen Nervensystem gehören",
             ["das Gehirn", "das somatische Nervensystem", "die Wirbelsäure", "das Rückenmark"],
             [0, 3]),
    Question(23, "Das parasympathische Nervensystem",
             ["steuert bewusst Reaktionen", "aktiviert den Körper zu Höchstleistungen („fight and flight“)",
              "steuert das anregende System", "bildet das Denkzentrum im Gehirn"],
             []),
    Question(24, "Nitriersäure besteht aus",
             ["Salzsäure", "Schwefelsäure", "Phosphorsäure", "Salpetersäure"],
             [1, 3]),
    Question(25, "Beim Nitrieren von Methan entsteht",
             ["ein Treibstoff", "ein Sprengstoff", "ein Medikament für Herzkranke", "Nitromethanoat"],
             [0]),
    Question(26, "2,4,6-Trinitrotoluen (TNT)",
             ["enthält weniger spezifische Energie (kJ/g) als Steinkohle",
              "kann schwerer als Nitroglycerin gezündet werden",
              "benötigt bei der Detonation die Zufuhr von Stickstoff zur Bildung nitroser Gase",
              "ist die Referenzsubstanz für die Sprengkraft von Kernwaffen"],
             [0, 1, 3]),
    Question(27, "2,4,6-Trinitrotoluen (TNT)",
             ["enthält mehr spezifische Energie (kJ/g) als Steinkohle",
              "kann leichter als Nitroglycerin gezündet werden",
              "benötigt bei der Detonation die Zufuhr von Luftsauerstoff",
              "ist die Referenzsubstanz für die Sprengkraft von Kernwaffen"],
             [3]),
    Question(29, "2,4,6-Trinitrotoluen (TNT)",
             ["enthält mehr spezifische Energie (kJ/g) als Staubzucker", "wird zur Gewinnung von Marmor verwendet",
              "benötigt bei der Detonation die Zufuhr von Luftsauerstoff", "ist ein hochbrisanter Sprengstoff"],
             [3]),
    Question(30, "Explodierende Stoffe haben eine Verbrennungsgeschwindigkeit",
             ["bis 300 m/s", "von 300 - 3.000 m/s", "über 3.000 m/s",
              "die geringer ist als die von detonierenden Stoffen"],
             [1, 3]),
    Question(31, "Deflagrierende Stoffe haben eine Verbrennungsgeschwindigkeit",
             ["bis 300 m/s", "von 300 - 3.000 m/s", "über 3.000 m/s",
              "die geringer ist als die von detonierenden Stoffen"],
             [0, 3]),
    Question(32, "Deflagrierende Stoffe haben eine Verbrennungsgeschwindigkeit",
             ["bis 300 m/s", "von 300 - 3.000 m/s", "über 3.000 m/s",
              "die größer ist als die von detonierenden Stoffen"],
             [0]),
    Question(33, "Detonierende Stoffe haben eine Verbrennungsgeschwindigkeit",
             ["bis 300 m/s", "von 300 - 3.000 m/s", "über 3.000 m/s",
              "die größer ist als die von explodierenden Stoffen"],
             [2, 3]),
    Question(34, "Hochrisante Sprengstoffe haben eine Verbrennungsgeschwindigkeit von",
             ["<300 m/s", ">300 m/s", "<3000 m/s", ">3000 m/s"],
             [1, 3]),
    Question(35, "Brisante Sprengstoffe haben eine Verbrennungsgeschwindigkeit von",
             ["<300 m/s", ">300 m/s", "<3000 m/s", ">3000 m/s"],
             [1, 2]),
    Question(36, "Eine Verbrennungsgeschwindigkeit von Sprengstoffen mit 700 m/s nennt man",
             ["Exposition", "Explosion", "Detonation", "Deflagration"],
             [1]),
    Question(37, "Eine Verbrennungsgeschwindigkeit von Sprengstoffen mit 6700 m/s nennt man",
             ["Exposition", "Explosion", "Detonation", "Deflagration"],
             [2]),
    Question(38, "Amine haben als funktionelle Gruppe",
             ["-NH4", "-NH3", "-NH2", "-NH"],
             [2]),
    Question(39, "Amide sind entstehen durch eine Verbindung von",
             ["einem Amin und einer Nitrogruppe", "einer organischen Säure und einem Amin",
              "einem Alkaloid mit einem Alkohol", "einem Amin und einem Aldehyd"],
             [1]),
    Question(40, "Amide liegen vor, wenn",
             ["die Hydroxygruppe (-OH) einer Carbonsäure (-COOH) durch eine Aminogruppe ersetzt wird.",
              "die Aminogruppe eines Proteins durch eine Hydroxygruppe (-OH) ersetzt wird.",
              "von Aminen Stickstoff (N) gegen Deuterium (D) ausgetauscht wird.",
              "der Sauerstoff einer Carboxylgruppe (=O) durch zwei Aminogruppen ersetzt wird."],
             [0]),
    Question(41, "Harnstoff wird aus folgenden Rohstoffen synthetisiert",
             ["Kohlendioxid und Wasser", "Kohlensäure und Ammoniak", "Harnsäure und Kohlendioxid",
              "Ammoniak und Wasser"],
             [1]),
    Question(42, "Harnstoff wird aus folgenden Rohstoffen synthetisiert",
             ["Kohlendioxid und Wasser", "Kohlendioxid und Ammoniak", "Harnsäure und Kohlendioxid",
              "Ammoniak und Wasser"],
             [1]),
    Question(43, "Harnstoff wird aus folgenden Rohstoffen synthetisiert",
             ["Kohlensäure und Wasser", "Kohlensäure und Ammoniak", "Harnsäure und Kohlendioxid",
              "Ammoniak und Wasser"],
             [1]),
    Question(44, "Harnstoff wird aus folgenden Rohstoffen synthetisiert",
             ["Kohlensäure und Wasser", "Kohlendioxid und Ammoniak", "Harnsäure und Kohlendioxid",
              "Ammoniak und Wasser"],
             [1]),
    Question(45, "Aminosäuren sind die Baustoffe von",
             ["Fetten", "Proteinen", "Eiweiß", "Kohlehydraten"],
             [1, 2]),
    Question(46, "Eine Aminosäure besitzt immer mindestens",
             ["eine –COOH - Gruppe", "eine –CH2-OH - Gruppe", "eine –NH2 - Gruppe", "ein N-Atom"],
             [0, 2, 3]),
    Question(47, "Eine Aminosäure besitzt immer mindestens",
             ["eine –COOH - Gruppe", "eine –CHO - Gruppe", "eine –NH3 - Gruppe", "ein N-Atom"],
             [0, 3]),
    Question(48, "Eine Aminosäure besitzt immer",
             ["eine –COOH - Gruppe", "eine –CHO - Gruppe", "eine –NH3 - Gruppe", "ein N-Atom"],
             [0, 3]),
    Question(49, "Proteine werden aufgebaut aus",
             ["Fettsäuren", "Lipiden", "Aminosäuren", "Nukleotiden"],
             [2]),
    Question(50, "Aminosäuren sind",
             ["Prolamin", "Glycin", "Cystein", "Glutamin"],
             [1, 2, 3]),
    Question(51, "Essentielle Aminosäuren sind",
             ["Leucin", "Valin", "Lysin", "Tryptophan"],
             [0, 1, 2, 3]),
    Question(52, "Zu den essentiellen Aminosäuren gehören",
             ["Lysin", "Tryptophan", "Aminin", "Glycin"],
             [0, 1]),
    Question(53, "Zu den Heterocyclen gehören",
             ["Furan", "Thiophen", "Pyrimidin", "Purin"],
             [0, 1, 2, 3]),
    Question(54, "Zu den Fünfringheterocylen gehören",
             ["Cyclopentan", "Pyrrolidin", "Pyrrol", "Pyridin"],
             [1, 2]),
    Question(55, "Zu den Fünfringheterocylen gehören",
             ["Pentan", "Hexan", "Pyrrol", "Pyridin"],
             [2]),
    Question(56, "Zu den Sechsringheterocylen gehören",
             ["Cyclohexan", "Pyrrolidin", "Pyrrol", "Pyridin"],
             [3]),
    Question(57, "Zu den biogenen makromolekularen Substanzen gehören",
             ["Biodiesel", "Cellulose", "Stärke", "Nylon"],
             [1, 2]),
    Question(58, "Kopierpapier besteht großteils aus",
             ["Zuckereinheiten", "Aminosäuren", "Fettsäuren", "Zellulose"],
             [3, 0]),
    Question(59, "Baumwolle besteht aus",
             ["Zuckereinheiten", "Aminosäuren", "Fettsäuren", "Kernbasen"],
             [0]),
    Question(60, "Cellulosenitrate wurden oder werden verwendet als Material für",
             ["Bekleidungsstoffe", "Filmmaterial", "Tennisschläger", "Treibladungen von Patronen"],
             [0, 1, 3]),
    Question(61, "Vollsynthetische Kunststoffe werden durch folgende Verfahren hergestellt",
             ["Polysubtraktion", "Polyaddition", "Polymerisation", "Polysynthetisation"],
             [1, 2]),
    Question(62, "Die gesundheitsrelevante Qualität von Kunststoffen hängt ab",
             ["vom Polymerisationsgrad", "vom Anteil der Weichmacher (v.a. Phtalate)",
              "vom Anteil unverbrauchter Radikalkettenstarter", "von der optischen Transparenz."],
             [1, 2]),
    Question(63, "Bei der Polykondensation wird meist folgender Stoff freigesetzt",
             ["Alkohol", "Carbonsäure", "Wasser", "Kohlendioxid"],
             [2]),
    Question(65, "Duromere sind im Gebrauchsbereich",
             ["elastisch", "hart", "spröde", "leicht formbar"],
             [1, 2]),
    Question(66, "Duromere sind im Gebrauchsbereich",
             ["elastisch", "hart", "flüssig", "leicht formbar"],
             [1]),
    Question(67, "Alkaloide sind immer organische",
             ["Alkohole", "Stickstoffverbindungen", "Kohlenstoffverbindungen", "Lösungsmittel"],
             [1, 2]),
    Question(68, "Alkaloide sind immer organische",
             ["Carbonsäuren", "Schwefelverbindungen", "Kohlenstoffverbindungen", "Lösungsmittel"],
             [2]),
    Question(69, "Zu den Alkaloiden gehören",
             ["Nikotin", "Koffein", "Alanin", "Protein"],
             [0, 1]),
    Question(70, "Zu den Alkaloiden gehören",
             ["Nikotin", "Koffein", "Atropin", "Protein"],
             [0, 1, 2]),
    Question(71, "Alkaloide sind in wässriger Lösung",
             ["alkalisch", "neutral", "Schiff´sche Säuren", "sauer"],
             [0]),
    Question(72, "Alkaloide sind in wässriger Lösung",
             ["alkalisch", "neutral", "Schiff´sche Basen", "sauer"],
             [0, 2]),
    Question(73, "Punsch benötigt als Inhaltsstoff unbedingt",
             ["Obstler", "Tee", "Alkohol", "Gewürze"],
             [1, 2, 3]),
    Question(74, "Jägertee („Jagatee“) benötigt als Inhaltsstoff unbedingt",
             ["einen Ausschank in Österreich", "Obstbrand", "Wein", "Gewürze"],
             [0, 1, 3]),
    Question(75, "Jägertee („Jagatee“) benötigt als Inhaltsstoff unbedingt",
             ["Obstbrand aus Beerenfrüchten", "Tee", "Alkohol", "Gewürze"],
             [1, 2, 3]),
    Question(76, "Eine Essigmutter bildet sich beim",
             ["Submersverfahren", "Immersverfahren", "Orleansverfahren", "Marseilleverfahren"],
             [2]),
    Question(77, "Einen Bioreaktor zur Herstellung von Essig benötigt man beim",
             ["Submersverfahren", "Immersverfahren", "Orleansverfahren", "Marseilleverfahren"],
             [0]),
    Question(78, "Bei der Titration von 10 mL Essig mit 8 mL 1M NaOH ergibt sich eine Konzentration von",
             ["4% Essigsäure (m/v) +/-1%", "5% Essigsäure (m/v) +/-1%", "6% Essigsäure (m/v) +/-1%",
              "7% Essigsäure (m/v) +/-1%"],
             [0, 1]),
    Question(79, "Bei der Titration von 1 mL Essig mit 6 mL 0,1M NaOH ergibt sich eine Konzentration von",
             ["4% Essigsäure (m/v) +/-1%", "5% Essigsäure (m/v) +/-1%", "6% Essigsäure (m/v) +/-1%",
              "7% Essigsäure (m/v) +/-1%"],
             [0]),
    Question(80, "Bei der Titration von 10 mL Essig mit 8 mL 1M NaOH ergibt sich eine Konzentration von",
             ["4% Essigsäure (m/v) +/-1%", "5% Essigsäure (m/v) +/-1%", "6% Essigsäure (m/v) +/-1%",
              "7% Essigsäure (m/v) +/-1%"],
             [0, 1]),
    Question(81, "Bei der Titration von 1 mL Essig mit 9 mL 0,1M NaOH ergibt sich eine Konzentration von",
             ["4% Essigsäure (m/v) +/-1%", "5% Essigsäure (m/v) +/-1%", "6% Essigsäure (m/v) +/-1%",
              "7% Essigsäure (m/v) +/-1%"],
             [1, 2]),
    Question(82, "Das funktionale C-Atom in Methanol hat die Oxidationszahl",
             ["-III", "-II", "-I", "0"],
             [1]),
    Question(83, "Das funktionale C-Atom in Methanal hat die Oxidationszahl",
             ["-III", "-II", "-I", "0"],
             [3]),
    Question(84, "Das funktionale C-Atom in Methansäure hat die Oxidationszahl",
             ["+III", "+II", "+I", "0"],
             [1]),
    Question(85, "Das funktionale C-Atom in Methan hat die Oxidationszahl",
             ["-IV", "-III", "-II", "-I"],
             [0]),
    Question(86, "Das funktionale C-Atom in Ethan hat die Oxidationszahl",
             ["-III", "-II", "-I", "0"],
             [0])
]
